version: "3"
services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - bundle_cache:/bundle
      - .:/app
    ports:
      - "3000:3000"
    env_file: .env
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  bundle_cache:
  postgres:
